// DO NOT EDIT THIS FILE.  IT IS AUTOMATICALLY GENERATED.
// longbow-generate-about 1.0.20160203.4a493d419377d4ffe96fea5d1422884673e9373e 2016-02-04T00:41:29Z

#include "longBow_About.h"

const char *longBow_What = "@(#)LongBow 1.0.20160203.4a493d419377d4ffe96fea5d1422884673e9373e 2016-02-04T00:41:29.555944\n@(#)\tCopyright (c) 2016, Xerox Corporation (Xerox)and Palo Alto Research Center (PARC)\n@(#)\tAll rights reserved.";

const char *
longBowAbout_Name(void)
{
    return "LongBow";
}

const char *
longBowAbout_Version(void)
{
    return "1.0.20160203.4a493d419377d4ffe96fea5d1422884673e9373e";
}

const char *
longBowAbout_About(void)
{
    return "LongBow 1.0.20160203.4a493d419377d4ffe96fea5d1422884673e9373e 2016-02-04T00:41:29.555944\nCopyright (c) 2016, Xerox Corporation (Xerox)and Palo Alto Research Center (PARC)\nAll rights reserved.\n";
}

const char *
longBowAbout_MiniNotice(void)
{
    return "Copyright (c) 2016, Xerox Corporation (Xerox)and Palo Alto Research Center (PARC)\nAll rights reserved.\n";
}

const char *
longBowAbout_ShortNotice(void)
{
    return "Copyright (c) 2016, Xerox Corporation (Xerox)and Palo Alto Research Center (PARC)\nAll rights reserved.\n\nRedistribution and use in source and binary forms, with or without\nmodification, are permitted provided that the following conditions are met:\n\n    * Redistributions of source code must retain the above copyright\n      notice, this list of conditions and the following disclaimer.\n    * Redistributions in binary form must reproduce the above copyright\n      notice, this list of conditions and the following disclaimer in the\n      documentation and/or other materials provided with the distribution.\n    * Patent rights are not granted under this agreement. Patent rights are\n      available under FRAND terms.\n\nTHIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS \"AS IS\" AND\nANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED\nWARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE\nDISCLAIMED. IN NO EVENT SHALL XEROX or PARC BE LIABLE FOR ANY\nDIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES\n(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;\nLOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND\nON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT\n(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS\nSOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n";
}

const char *
longBowAbout_LongNotice(void)
{
    return "Copyright (c) 2016, Xerox Corporation (Xerox)and Palo Alto Research Center (PARC)\nAll rights reserved.\n\nRedistribution and use in source and binary forms, with or without\nmodification, are permitted provided that the following conditions are met:\n\n    * Redistributions of source code must retain the above copyright\n      notice, this list of conditions and the following disclaimer.\n    * Redistributions in binary form must reproduce the above copyright\n      notice, this list of conditions and the following disclaimer in the\n      documentation and/or other materials provided with the distribution.\n    * Patent rights are not granted under this agreement. Patent rights are\n      available under FRAND terms.\n\nTHIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS \"AS IS\" AND\nANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED\nWARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE\nDISCLAIMED. IN NO EVENT SHALL XEROX or PARC BE LIABLE FOR ANY\nDIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES\n(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;\nLOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND\nON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT\n(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS\nSOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n";
}

