// DO NOT EDIT THIS FILE.  IT IS AUTOMATICALLY GENERATED.
// longbow-generate-about 1.0.20160203.4a493d419377d4ffe96fea5d1422884673e9373e 2016-02-04T00:41:29Z

#ifndef longBow_About_h
#define longBow_About_h
/**
 * Embedded string containing information for the what(1) command.
 *
 */
extern const char *longBow_What;

/**
 * Return the name as a C string.
 *
 * @return The name as a C string.
 */
const char *longBowAbout_Name(void);

/**
 * Return the version as a C string.
 *
 * @return The version as a C string.
 */
const char *longBowAbout_Version(void);

/**
 * Return the About text as a C string.
 *
 * @return The About text as a C string.
 */
const char *longBowAbout_About(void);

/**
 * Return the minimum copyright notice as a C string.
 *
 * @return The minimum copyright notice as a C string.
 */
const char *longBowAbout_MiniNotice(void);

/**
 * Return the short copyright notice as a C string.
 *
 * @return The short copyright notice as a C string.
 */
const char *longBowAbout_ShortNotice(void);

/**
 * Return the long copyright notice as a C string.
 *
 * @return The long copyright notice as a C string.
 */
const char *longBowAbout_LongNotice(void);

#endif // longBow_About_h
